INSERT INTO funcao_integrante (
    cd_esporte,
    nm_funcao,
    ds_funcao
) VALUES 
(2, 'Goleiro', 'Defensor principal'),
(2, 'Fixo', 'Defensor central'),
(2, 'Alas Esquerdo', 'Atuam pelas respectivas laterais'),
(2, 'Alas Direito', 'Atuam pelas respectivas laterais'),
(2, 'Pivô', 'Atacante de referência'),
(3, 'Armador', 'Organiza o jogo'),
(3, 'Ala-Armador', 'Arremessos de três pontos e infiltrações rápidas na defesa.'),
(3, 'Ala', 'Jogador Versátil'),
(3, 'Ala-Pivô', 'Disputar rebotes, bloquear adversários e pontuar perto ou a média distância da cesta.'),
(3, 'Pivô', 'Joga próximo à cesta'),
(5, 'Goleiro', 'Defensor principal'),
(5, 'Ponta Esquerda', 'Atua bem aberto, no canto da quadra, próximo à linha de fundo e à linha lateral.'),
(5, 'Ponta Direita', 'Atua bem aberto, no canto da quadra, próximo à linha de fundo e à linha lateral.'),
(5, 'Armador Lateral Esquerdo', 'Atua na região intermediária, entre o armador central e o ponta.'),
(5, 'Armador Lateral Direito', 'Atua na região intermediária, entre o armador central e o ponta.'),
(5, 'Armador Central', 'Responsável por organizar e comandar as jogadas de ataque no centro da quadra'),
(5, 'Pivô', 'jogador de ataque que atua bem no meio da defesa adversária, geralmente na linha dos 6 metros, com a função de abrir espaços e finalizar'),
(8, 'Levantador', 'Organiza o ataque'),
(8, 'Ponteiro A', 'Atacam pelas pontas e ajudam na recepção'),
(8, 'Ponteiro B', 'Atacam pelas pontas e ajudam na recepção'),
(9, 'Oposto A', 'Principais pontuadores de ataque'),
(9, 'Oposto B', 'Principais pontuadores de ataque'),
(9, 'Central', 'Ataca pelo meio e lidera o bloqueio'),
(9, 'Libero', 'Especialista defensivo que não ataca nem saca');