INSERT INTO funcao_integrante (
    cd_funcao_integrante,
    cd_esporte,
    nm_funcao,
    ds_funcao
) VALUES 
( 1, 2, "Goleiro", "Defensor principal"),
( 2, 2, "Fixo", "Defensor central"),
( 3, 2, "Alas Esquerdo", "Atuam pelas respectivas laterais"),
( 4, 2, "Alas Direito", "Atuam pelas respectivas laterais"),
( 5, 2, "Pivô", "Atacante de referência"),
( 6, 3, "Armador", "Organiza o jogo"),
( 7, 3, "Ala-Armador", "Arremessos de três pontos e infiltrações rápidas na defesa."),
( 8, 3, "Ala", "Jogador Versátil"),
( 9, 3, "Ala-Pivô", "Disputar rebotes, bloquear adversários e pontuar perto ou a média distância da cesta."),
( 10, 3, "Pivô", "Joga próximo à cesta"),
( 11, 5, "Goleiro", "Defensor principal"),
( 12, 5, "Ponta Esquerda", "Atua bem aberto, no canto da quadra, próximo à linha de fundo e à linha lateral."),
( 13, 5, "Ponta Direita", "Atua bem aberto, no canto da quadra, próximo à linha de fundo e à linha lateral."),
( 14, 5, "Armador Lateral Esquerdo", "Atua na região intermediária, entre o armador central e o ponta."),
( 15, 5, "Armador Lateral Direito", "Atua na região intermediária, entre o armador central e o ponta."),
( 16, 5, "Armador Central", "Responsável por organizar e comandar as jogadas de ataque no centro da quadra"),
( 17, 5, "Pivô", "jogador de ataque que atua bem no meio da defesa adversária, geralmente na linha dos 6 metros, com a função de abrir espaços e finalizar"),
( 18, 8, "Levantador", "Organiza o ataque"),
( 19, 8, "Ponteiro A", "Atacam pelas pontas e ajudam na recepção"),
( 20, 8, "Ponteiro B", "Atacam pelas pontas e ajudam na recepção"),
( 21, 9, "Oposto A", "Principais pontuadores de ataque"),
( 22, 9, "Oposto B", "Principais pontuadores de ataque"),
( 23, 9, "Central", "Ataca pelo meio e lidera o bloqueio"),
( 24, 9, "Libero", "Especialista defensivo que não ataca nem saca"),
( 25, 9, "", "")